/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import clases.cuenta;
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import static java.awt.image.ImageObserver.SOMEBITS;
import javax.swing.ButtonGroup;
import rojerusan.RSNotifyFade;

/**
 *
 * @author Nahomi
 */
public class Cuenta extends javax.swing.JFrame {

    public cuenta cu;
    /**
     * Creates new form Cuenta
     */
    public Cuenta() {
        initComponents();
        this.setLocationRelativeTo(null);
        txtnombreC.setBackground(new Color(0,0,0,0));
        Shape forma = new RoundRectangle2D.Double(0,0,this.getBounds().width, this.getBounds().height,35,35);
        AWTUtilities.setWindowShape(this, forma);
        ButtonGroup grupo_activo = new ButtonGroup();
        ButtonGroup grupo_corriente = new ButtonGroup();
        grupo_activo.add(btnactivo);
        grupo_activo.add(btnpasivo);
        grupo_corriente.add(btncorriente);
        grupo_corriente.add(btnncorriente);
        cu = new cuenta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtnombreC = new javax.swing.JTextField();
        btnncorriente = new javax.swing.JRadioButton();
        btncorriente = new javax.swing.JRadioButton();
        btnpasivo = new javax.swing.JRadioButton();
        btnactivo = new javax.swing.JRadioButton();
        rSMaterialButtonRectangle5 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle6 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle3 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle4 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonCircle1 = new rojerusan.RSMaterialButtonCircle();
        jLabel2 = new javax.swing.JLabel();
        btnminimizar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btncerrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 120, -1));

        txtnombreC.setFont(new java.awt.Font("Microsoft YaHei UI Light", 0, 18)); // NOI18N
        txtnombreC.setBorder(null);
        txtnombreC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnombreCKeyReleased(evt);
            }
        });
        jPanel1.add(txtnombreC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 310, 30));

        btnncorriente.setBackground(new java.awt.Color(214, 246, 255));
        btnncorriente.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        btnncorriente.setText("  No Corriente");
        jPanel1.add(btnncorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 200, 30));

        btncorriente.setBackground(new java.awt.Color(214, 246, 255));
        btncorriente.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        btncorriente.setSelected(true);
        btncorriente.setText("    Corriente");
        jPanel1.add(btncorriente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 260, 190, 30));

        btnpasivo.setBackground(new java.awt.Color(214, 246, 255));
        btnpasivo.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        btnpasivo.setText("       Pasivo");
        jPanel1.add(btnpasivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 180, 30));

        btnactivo.setBackground(new java.awt.Color(214, 246, 255));
        btnactivo.setFont(new java.awt.Font("Microsoft JhengHei UI", 0, 24)); // NOI18N
        btnactivo.setSelected(true);
        btnactivo.setText("       Activo");
        jPanel1.add(btnactivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 190, 30));

        rSMaterialButtonRectangle5.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle5.setEnabled(false);
        jPanel1.add(rSMaterialButtonRectangle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 220, 50));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle1.setEnabled(false);
        jPanel1.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 220, 50));

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle2.setEnabled(false);
        jPanel1.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 330, 50));

        rSMaterialButtonRectangle6.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle6.setEnabled(false);
        jPanel1.add(rSMaterialButtonRectangle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 220, 50));

        rSMaterialButtonRectangle3.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle3.setEnabled(false);
        jPanel1.add(rSMaterialButtonRectangle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, 220, 50));

        rSMaterialButtonRectangle4.setBackground(new java.awt.Color(0, 52, 102));
        rSMaterialButtonRectangle4.setText("Guardar");
        rSMaterialButtonRectangle4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle4ActionPerformed(evt);
            }
        });
        jPanel1.add(rSMaterialButtonRectangle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 200, 60));

        rSMaterialButtonCircle1.setBackground(new java.awt.Color(255, 255, 255));
        rSMaterialButtonCircle1.setBorder(null);
        rSMaterialButtonCircle1.setBorderPainted(false);
        rSMaterialButtonCircle1.setFocusPainted(false);
        rSMaterialButtonCircle1.setSelected(true);
        jPanel1.add(rSMaterialButtonCircle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 500, 300));

        jLabel2.setBackground(new java.awt.Color(252, 253, 255));
        jLabel2.setOpaque(true);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 570, 150));

        btnminimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/general/icons8_Chevron_Down_35px.png"))); // NOI18N
        btnminimizar.setBorder(null);
        btnminimizar.setBorderPainted(false);
        btnminimizar.setContentAreaFilled(false);
        btnminimizar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/general/icons8_Chevron_Down_55px.png"))); // NOI18N
        btnminimizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnminimizarMouseClicked(evt);
            }
        });
        jPanel1.add(btnminimizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 70, 57));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei Light", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nueva Cuenta");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 240, 70));

        btncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/general/icons8_Cancel_35px_1.png"))); // NOI18N
        btncerrar.setBorderPainted(false);
        btncerrar.setContentAreaFilled(false);
        btncerrar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/general/icons8_Cancel_55px_1.png"))); // NOI18N
        btncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrarMouseClicked(evt);
            }
        });
        jPanel1.add(btncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 0, -1, 57));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondos/029ea9134e18f1b2ff843d54952a3c88.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 562, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtnombreCKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreCKeyReleased

    }//GEN-LAST:event_txtnombreCKeyReleased

    private void rSMaterialButtonRectangle4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle4ActionPerformed
        String nombre = txtnombreC.getText();
        boolean activo;
        if(btnactivo.isSelected()) activo = true;
        else activo = false;
        boolean corriente;
        if(btncorriente.isSelected()) corriente = true;
        else corriente = false;
        if(cu.ingresarCuenta(nombre, activo, corriente))
        {
            new rojerusan.RSNotifyFade("¡ACEPTADA!", "Ingreso Correcto", Color.WHITE, Color.BLACK, Color.BLACK, SOMEBITS, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.SUCCESS).setVisible(true);
            this.dispose();
        }
        else
        {
            new rojerusan.RSNotifyFade("¡ERROR!", "Ingreso incorrecto, o cuenta repetida", Color.white, Color.black, Color.black, SOMEBITS, RSNotifyFade.PositionNotify.BottomRight, RSNotifyFade.TypeNotify.ERROR).setVisible(true);
        }
    }//GEN-LAST:event_rSMaterialButtonRectangle4ActionPerformed

    private void btnminimizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminimizarMouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnminimizarMouseClicked

    private void btncerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrarMouseClicked
        this.dispose();
        //System.exit(0);
    }//GEN-LAST:event_btncerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnactivo;
    private javax.swing.JButton btncerrar;
    private javax.swing.JRadioButton btncorriente;
    private javax.swing.JButton btnminimizar;
    private javax.swing.JRadioButton btnncorriente;
    private javax.swing.JRadioButton btnpasivo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private rojerusan.RSMaterialButtonCircle rSMaterialButtonCircle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle3;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle4;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle5;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle6;
    private javax.swing.JTextField txtnombreC;
    // End of variables declaration//GEN-END:variables
}
