/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author alex
 */
public class ingreso_inv extends javax.swing.JFrame {

    /**
     * Creates new form ingreso_inv
     */
    public ingreso_inv() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setSize(600, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtDes = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        txtCant = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        cmbDep = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbDonado = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbFungible = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Código");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(12, 54, 49, 15);
        getContentPane().add(txtCodigo);
        txtCodigo.setBounds(73, 52, 114, 19);

        jLabel2.setText("Descripción");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(12, 89, 82, 15);

        txtDes.setColumns(20);
        txtDes.setRows(5);
        getContentPane().add(txtDes);
        txtDes.setBounds(100, 90, 220, 75);

        jLabel3.setText("Cantidad");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(12, 183, 64, 15);
        getContentPane().add(txtCant);
        txtCant.setBounds(88, 181, 52, 19);

        jLabel4.setText("Precio");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(178, 185, 44, 15);
        getContentPane().add(txtPrecio);
        txtPrecio.setBounds(234, 181, 52, 19);

        cmbDep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(cmbDep);
        cmbDep.setBounds(440, 180, 90, 24);

        jLabel5.setText("Departamento");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(328, 183, 103, 15);

        jLabel6.setText("Estado");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 240, 51, 20);

        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bueno", "Malo" }));
        getContentPane().add(cmbEstado);
        cmbEstado.setBounds(70, 240, 73, 24);

        jLabel7.setText("Donado");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(180, 240, 60, 20);

        cmbDonado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        getContentPane().add(cmbDonado);
        cmbDonado.setBounds(250, 240, 47, 24);

        jLabel8.setText("Fungible");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 240, 70, 15);

        cmbFungible.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sí", "No" }));
        getContentPane().add(cmbFungible);
        cmbFungible.setBounds(410, 240, 71, 24);

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 290, 120, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String codigo = txtCodigo.getText();
        String descripcion = txtDes.getText();
        int cantidad = Integer.parseInt(txtCant.getText());
        double preciou = Double.parseDouble(txtPrecio.getText());
        double preciot = cantidad*preciou;
        String departamento = cmbDep.getSelectedItem().toString();
        String estado = cmbEstado.getSelectedItem().toString();
        String donado = cmbDonado.getSelectedItem().toString();
        String fungible = cmbFungible.getSelectedItem().toString();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ingreso_inv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ingreso_inv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ingreso_inv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ingreso_inv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ingreso_inv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDep;
    private javax.swing.JComboBox<String> cmbDonado;
    private javax.swing.JComboBox<String> cmbEstado;
    private javax.swing.JComboBox<String> cmbFungible;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCant;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextArea txtDes;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
