/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import rojerusan.RSPanelsSlider;

/**
 *
 * @author Nahomi
 */
public class Pacientes_Consultas extends javax.swing.JFrame {

    /**
     * Creates new form Pacientes_Consultas
     */
    public Pacientes_Consultas() {
        initComponents();
        Shape forma = new RoundRectangle2D.Double(0,0,this.getBounds().width, this.getBounds().height,35,35);
        AWTUtilities.setWindowShape(this, forma);
        this.setLocationRelativeTo(null);
        transparencia();
        
    }
    private void transparencia()
    {
        txtNombrep.setBackground(new Color(0,0,0,0));
        txtApellidop.setBackground(new Color(0,0,0,0));
        btnminimizar3.setOpaque(false);
        btnminimizar3.setBorderPainted(false);
        btnminimizar3.setContentAreaFilled(false);
        btncerrar3.setOpaque(false);
        btncerrar3.setBorderPainted(false);
        btncerrar3.setContentAreaFilled(false);
        btnhome2.setOpaque(false);
        btnhome2.setBorderPainted(false);
        btnhome2.setContentAreaFilled(false);
        txttelemep.setBackground(new Color(0,0,0,0));
        txtnombrep.setBackground(new Color(0,0,0,0));
        txtapellidop.setBackground(new Color(0,0,0,0));
        txtlugop.setBackground(new Color(0,0,0,0));
        txtcomunidadp.setBackground(new Color(0,0,0,0));
        txtestaturap.setBackground(new Color(0,0,0,0));
        txtpesop.setBackground(new Color(0,0,0,0));
        txtdpi.setBackground(new Color(0,0,0,0));
        txredada.setBackground(new Color(0,0,0,0));
        txtedadm.setBackground(new Color(0,0,0,0));
        txtedadd.setBackground(new Color(0,0,0,0));
        txttelefonop.setBackground(new Color(0,0,0,0));
        cmbalergiasp.setBackground(new Color(0,0,0,0));
        cmbtipos.setBackground(new Color(0,0,0,0));
        cmbsexop.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        rSPanelsSlider1 = new rojerusan.RSPanelsSlider();
        IngP = new javax.swing.JPanel();
        txtApellidop = new javax.swing.JTextField();
        btnconsulta = new rojerusan.RSMaterialButtonRectangle();
        btnNp = new rojerusan.RSMaterialButtonRectangle();
        txtNombrep = new javax.swing.JTextField();
        rSMaterialButtonRectangle3 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle4 = new rojerusan.RSMaterialButtonRectangle();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        scrollgai1 = new javax.swing.JScrollPane();
        tablePaciente = new rojerusan.RSTableMetro();
        jLabel17 = new javax.swing.JLabel();
        btnhome2 = new javax.swing.JButton();
        btnminimizar3 = new javax.swing.JButton();
        btncerrar3 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        IngresarnP = new javax.swing.JPanel();
        btnhome3 = new javax.swing.JButton();
        btnminimizar4 = new javax.swing.JButton();
        btncerrar4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        txttelemep = new javax.swing.JTextField();
        txtnombrep = new javax.swing.JTextField();
        txtapellidop = new javax.swing.JTextField();
        txtlugop = new javax.swing.JTextField();
        txtcomunidadp = new javax.swing.JTextField();
        txtestaturap = new javax.swing.JTextField();
        txtpesop = new javax.swing.JTextField();
        txtdpi = new javax.swing.JTextField();
        txredada = new javax.swing.JTextField();
        txtedadm = new javax.swing.JTextField();
        txtedadd = new javax.swing.JTextField();
        txttelefonop = new javax.swing.JTextField();
        cmbalergiasp = new javax.swing.JComboBox<>();
        cmbtipos = new javax.swing.JComboBox<>();
        cmbsexop = new javax.swing.JComboBox<>();
        fechanp = new rojeru_san.componentes.RSDateChooser();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle2 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle5 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle6 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle7 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle8 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle9 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle10 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle11 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle12 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle13 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle14 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle15 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle16 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle19 = new rojerusan.RSMaterialButtonRectangle();
        rSMaterialButtonRectangle21 = new rojerusan.RSMaterialButtonRectangle();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        rSMaterialButtonRectangle17 = new rojerusan.RSMaterialButtonRectangle();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 779));
        jPanel1.setLayout(new java.awt.CardLayout());

        IngP.setName("IngP"); // NOI18N
        IngP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApellidop.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        txtApellidop.setBorder(null);
        IngP.add(txtApellidop, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 245, 280, 40));

        btnconsulta.setText("Consulta");
        IngP.add(btnconsulta, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 240, 210, 60));

        btnNp.setText("Nuevo Paciente");
        btnNp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNpMouseClicked(evt);
            }
        });
        IngP.add(btnNp, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, 210, 60));

        txtNombrep.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        txtNombrep.setBorder(null);
        IngP.add(txtNombrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 193, 280, 40));

        rSMaterialButtonRectangle3.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle3.setEnabled(false);
        IngP.add(rSMaterialButtonRectangle3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 320, 50));

        rSMaterialButtonRectangle4.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle4.setEnabled(false);
        IngP.add(rSMaterialButtonRectangle4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 320, 50));

        jLabel20.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel20.setText("Apellidos:");
        IngP.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 150, 30));

        jLabel19.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel19.setText("Nombres:");
        IngP.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 150, 30));

        tablePaciente = new rojerusan.RSTableMetro(){
            public boolean isCellEditable(int rowIndex, int ColIndex){
                return false;
            }
        };
        tablePaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombres", "Apellidos", "Edad", "DPI/CUI"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePaciente.setColorBackgoundHead(new java.awt.Color(22, 54, 77));
        tablePaciente.setColorBordeFilas(new java.awt.Color(255, 255, 255));
        tablePaciente.setColorBordeHead(new java.awt.Color(255, 255, 255));
        tablePaciente.setColorFilasBackgound1(new java.awt.Color(163, 214, 249));
        tablePaciente.setColorFilasBackgound2(new java.awt.Color(255, 255, 255));
        tablePaciente.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        tablePaciente.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        tablePaciente.setColorSelBackgound(new java.awt.Color(22, 54, 77));
        tablePaciente.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        tablePaciente.setFuenteFilas(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        tablePaciente.setFuenteFilasSelect(new java.awt.Font("Yu Gothic UI Light", 0, 18)); // NOI18N
        tablePaciente.setFuenteHead(new java.awt.Font("Yu Gothic UI Light", 1, 18)); // NOI18N
        tablePaciente.setGrosorBordeFilas(0);
        tablePaciente.setGrosorBordeHead(0);
        tablePaciente.setRowHeight(22);
        tablePaciente.getTableHeader().setReorderingAllowed(false);
        scrollgai1.setViewportView(tablePaciente);

        IngP.add(scrollgai1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, 910, 430));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondos/ingp.png"))); // NOI18N
        IngP.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 59, 1280, 720));

        btnhome2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/general/icons8_Home_35px.png"))); // NOI18N
        btnhome2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/general/icons8_Home_55px.png"))); // NOI18N
        btnhome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome2MouseClicked(evt);
            }
        });
        IngP.add(btnhome2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1056, 0, 80, 60));

        btnminimizar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/general/icons8_Chevron_Down_35px.png"))); // NOI18N
        btnminimizar3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/general/icons8_Chevron_Down_55px.png"))); // NOI18N
        btnminimizar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnminimizar3MouseClicked(evt);
            }
        });
        btnminimizar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminimizar3ActionPerformed(evt);
            }
        });
        IngP.add(btnminimizar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, -1, 57));

        btncerrar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/general/icons8_Cancel_35px_1.png"))); // NOI18N
        btncerrar3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/general/icons8_Cancel_55px_1.png"))); // NOI18N
        btncerrar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrar3MouseClicked(evt);
            }
        });
        btncerrar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrar3ActionPerformed(evt);
            }
        });
        IngP.add(btncerrar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, -1, 57));

        jLabel18.setBackground(new java.awt.Color(0, 54, 102));
        jLabel18.setOpaque(true);
        IngP.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1290, 60));

        rSPanelsSlider1.add(IngP, "card5");

        IngresarnP.setName("IngresarnP"); // NOI18N
        IngresarnP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnhome3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/general/icons8_Home_35px.png"))); // NOI18N
        btnhome3.setBorder(null);
        btnhome3.setBorderPainted(false);
        btnhome3.setContentAreaFilled(false);
        btnhome3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/general/icons8_Home_55px.png"))); // NOI18N
        btnhome3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnhome3MouseClicked(evt);
            }
        });
        IngresarnP.add(btnhome3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1056, 0, 80, 60));

        btnminimizar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/general/icons8_Chevron_Down_35px.png"))); // NOI18N
        btnminimizar4.setBorder(null);
        btnminimizar4.setBorderPainted(false);
        btnminimizar4.setContentAreaFilled(false);
        btnminimizar4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/general/icons8_Chevron_Down_55px.png"))); // NOI18N
        btnminimizar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnminimizar4MouseClicked(evt);
            }
        });
        btnminimizar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnminimizar4ActionPerformed(evt);
            }
        });
        IngresarnP.add(btnminimizar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 70, 57));

        btncerrar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/general/icons8_Cancel_35px_1.png"))); // NOI18N
        btncerrar4.setBorder(null);
        btncerrar4.setBorderPainted(false);
        btncerrar4.setContentAreaFilled(false);
        btncerrar4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconos/general/icons8_Cancel_55px_1.png"))); // NOI18N
        btncerrar4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btncerrar4MouseClicked(evt);
            }
        });
        btncerrar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncerrar4ActionPerformed(evt);
            }
        });
        IngresarnP.add(btncerrar4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 0, 70, 57));

        jLabel21.setBackground(new java.awt.Color(0, 54, 102));
        jLabel21.setOpaque(true);
        IngresarnP.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1290, 60));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel1.setText("Teléfono/celular");
        IngresarnP.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 470, 200, 50));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel2.setText("Nombres:");
        IngresarnP.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel3.setText("Apellidos:");
        IngresarnP.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 290, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel4.setText("DPI/CUI:");
        IngresarnP.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel5.setText("nacimiento:");
        IngresarnP.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 370, 150, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel6.setText("Edad en años:");
        IngresarnP.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, -1, -1));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel7.setText("Edad en meses:");
        IngresarnP.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, -1, -1));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel8.setText("Edad en días:");
        IngresarnP.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 430, -1, 40));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel9.setText("Lugar de Origen:");
        IngresarnP.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 560, -1, -1));

        jLabel10.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel10.setText("Comunidad:");
        IngresarnP.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 650, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel11.setText("Tipo de Sangre:");
        IngresarnP.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 280, -1, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel12.setText("Estatura:");
        IngresarnP.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 490, -1, -1));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel13.setText("Peso:");
        IngresarnP.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 540, -1, -1));

        jLabel14.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel14.setText("Sexo:");
        IngresarnP.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 590, -1, -1));

        jLabel15.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel15.setText("Alergias:");
        IngresarnP.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 640, -1, -1));

        jLabel16.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel16.setText("Teléfono/celular:");
        IngresarnP.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 430, -1, -1));

        txttelemep.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        txttelemep.setBorder(null);
        IngresarnP.add(txttelemep, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 180, 30));

        txtnombrep.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        txtnombrep.setBorder(null);
        IngresarnP.add(txtnombrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, 240, 30));

        txtapellidop.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        txtapellidop.setBorder(null);
        IngresarnP.add(txtapellidop, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, 240, 30));

        txtlugop.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        txtlugop.setBorder(null);
        IngresarnP.add(txtlugop, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, 380, 30));

        txtcomunidadp.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        txtcomunidadp.setBorder(null);
        IngresarnP.add(txtcomunidadp, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 650, 230, 30));

        txtestaturap.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        txtestaturap.setBorder(null);
        IngresarnP.add(txtestaturap, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 490, 100, 30));

        txtpesop.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        txtpesop.setBorder(null);
        IngresarnP.add(txtpesop, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 540, 100, 30));

        txtdpi.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        txtdpi.setBorder(null);
        IngresarnP.add(txtdpi, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 230, 230, 30));

        txredada.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        txredada.setBorder(null);
        IngresarnP.add(txredada, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 90, 30));

        txtedadm.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        txtedadm.setBorder(null);
        IngresarnP.add(txtedadm, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, 90, 30));

        txtedadd.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        txtedadd.setBorder(null);
        IngresarnP.add(txtedadd, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 440, 90, 30));

        txttelefonop.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        txttelefonop.setBorder(null);
        IngresarnP.add(txttelefonop, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, 190, 30));

        cmbalergiasp.setBackground(new java.awt.Color(0, 52, 102));
        cmbalergiasp.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        cmbalergiasp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        IngresarnP.add(cmbalergiasp, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 640, 160, -1));

        cmbtipos.setBackground(new java.awt.Color(0, 52, 102));
        cmbtipos.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        cmbtipos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        IngresarnP.add(cmbtipos, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 280, 130, -1));

        cmbsexop.setBackground(new java.awt.Color(0, 52, 102));
        cmbsexop.setFont(new java.awt.Font("Microsoft YaHei Light", 0, 18)); // NOI18N
        cmbsexop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        IngresarnP.add(cmbsexop, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 590, 160, -1));
        IngresarnP.add(fechanp, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle1.setEnabled(false);
        IngresarnP.add(rSMaterialButtonRectangle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 630, 190, 50));

        rSMaterialButtonRectangle2.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle2.setEnabled(false);
        IngresarnP.add(rSMaterialButtonRectangle2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 280, 50));

        rSMaterialButtonRectangle5.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle5.setEnabled(false);
        IngresarnP.add(rSMaterialButtonRectangle5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 280, 50));

        rSMaterialButtonRectangle6.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle6.setEnabled(false);
        IngresarnP.add(rSMaterialButtonRectangle6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 590, 400, 50));

        rSMaterialButtonRectangle7.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle7.setEnabled(false);
        IngresarnP.add(rSMaterialButtonRectangle7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 640, 250, 50));

        rSMaterialButtonRectangle8.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle8.setEnabled(false);
        IngresarnP.add(rSMaterialButtonRectangle8, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 480, 170, 50));

        rSMaterialButtonRectangle9.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle9.setEnabled(false);
        IngresarnP.add(rSMaterialButtonRectangle9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 530, 170, 50));

        rSMaterialButtonRectangle10.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle10.setEnabled(false);
        IngresarnP.add(rSMaterialButtonRectangle10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1440, 400, 150, 50));

        rSMaterialButtonRectangle11.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle11.setEnabled(false);
        IngresarnP.add(rSMaterialButtonRectangle11, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 580, 190, 50));

        rSMaterialButtonRectangle12.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle12.setEnabled(false);
        IngresarnP.add(rSMaterialButtonRectangle12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 420, 210, 50));

        rSMaterialButtonRectangle13.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle13.setEnabled(false);
        IngresarnP.add(rSMaterialButtonRectangle13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 490, 200, 50));

        rSMaterialButtonRectangle14.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle14.setEnabled(false);
        rSMaterialButtonRectangle14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle14ActionPerformed(evt);
            }
        });
        IngresarnP.add(rSMaterialButtonRectangle14, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 330, 170, 50));

        rSMaterialButtonRectangle15.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle15.setEnabled(false);
        IngresarnP.add(rSMaterialButtonRectangle15, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 250, 50));

        rSMaterialButtonRectangle16.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle16.setEnabled(false);
        IngresarnP.add(rSMaterialButtonRectangle16, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 270, 170, 50));

        rSMaterialButtonRectangle19.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle19.setEnabled(false);
        IngresarnP.add(rSMaterialButtonRectangle19, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 430, 170, 50));

        rSMaterialButtonRectangle21.setBackground(new java.awt.Color(186, 240, 255));
        rSMaterialButtonRectangle21.setEnabled(false);
        IngresarnP.add(rSMaterialButtonRectangle21, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 380, 170, 50));

        jLabel23.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel23.setText(" de emergencia:");
        IngresarnP.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 200, 60));

        jLabel24.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 24)); // NOI18N
        jLabel24.setText("Fecha de");
        IngresarnP.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 110, -1));

        jLabel25.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel25.setText("Años");
        IngresarnP.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 345, -1, -1));

        jLabel26.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel26.setText("Meses");
        IngresarnP.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(965, 392, -1, -1));

        jLabel27.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel27.setText("días");
        IngresarnP.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(973, 443, -1, -1));

        jLabel28.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel28.setText("cm");
        IngresarnP.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(983, 492, -1, -1));

        jLabel29.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel29.setText("lb");
        IngresarnP.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 542, -1, -1));

        rSMaterialButtonRectangle17.setText("Consulta");
        IngresarnP.add(rSMaterialButtonRectangle17, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 610, 190, 80));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondos/ingp.png"))); // NOI18N
        IngresarnP.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 1280, 720));

        rSPanelsSlider1.add(IngresarnP, "card3");

        jPanel1.add(rSPanelsSlider1, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnhome2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome2MouseClicked
        Interfaz in = new Interfaz();
        in.setVisible(true);
    }//GEN-LAST:event_btnhome2MouseClicked

    private void btnminimizar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminimizar3MouseClicked
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnminimizar3MouseClicked

    private void btnminimizar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminimizar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnminimizar3ActionPerformed

    private void btncerrar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrar3MouseClicked
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btncerrar3MouseClicked

    private void btncerrar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncerrar3ActionPerformed

    private void btnhome3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnhome3MouseClicked
        Interfaz in = new Interfaz();
        in.setVisible(true);
    }//GEN-LAST:event_btnhome3MouseClicked

    private void btnminimizar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnminimizar4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnminimizar4MouseClicked

    private void btnminimizar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnminimizar4ActionPerformed
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnminimizar4ActionPerformed

    private void btncerrar4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btncerrar4MouseClicked
        this.dispose();
        System.exit(0);
    }//GEN-LAST:event_btncerrar4MouseClicked

    private void btncerrar4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncerrar4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btncerrar4ActionPerformed

    private void rSMaterialButtonRectangle14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rSMaterialButtonRectangle14ActionPerformed

    private void btnNpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNpMouseClicked
        rSPanelsSlider1.setPanelSlider(IngresarnP, RSPanelsSlider.DIRECT.LEFT);
    }//GEN-LAST:event_btnNpMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pacientes_Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pacientes_Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pacientes_Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pacientes_Consultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pacientes_Consultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IngP;
    private javax.swing.JPanel IngresarnP;
    private rojerusan.RSMaterialButtonRectangle btnNp;
    private javax.swing.JButton btncerrar3;
    private javax.swing.JButton btncerrar4;
    private rojerusan.RSMaterialButtonRectangle btnconsulta;
    private javax.swing.JButton btnhome2;
    private javax.swing.JButton btnhome3;
    private javax.swing.JButton btnminimizar3;
    private javax.swing.JButton btnminimizar4;
    private javax.swing.JComboBox<String> cmbalergiasp;
    private javax.swing.JComboBox<String> cmbsexop;
    private javax.swing.JComboBox<String> cmbtipos;
    private rojeru_san.componentes.RSDateChooser fechanp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle10;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle11;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle12;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle13;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle14;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle15;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle16;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle17;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle19;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle2;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle21;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle3;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle4;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle5;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle6;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle7;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle8;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle9;
    private rojerusan.RSPanelsSlider rSPanelsSlider1;
    private javax.swing.JScrollPane scrollgai1;
    private rojerusan.RSTableMetro tablePaciente;
    private javax.swing.JTextField txredada;
    private javax.swing.JTextField txtApellidop;
    private javax.swing.JTextField txtNombrep;
    private javax.swing.JTextField txtapellidop;
    private javax.swing.JTextField txtcomunidadp;
    private javax.swing.JTextField txtdpi;
    private javax.swing.JTextField txtedadd;
    private javax.swing.JTextField txtedadm;
    private javax.swing.JTextField txtestaturap;
    private javax.swing.JTextField txtlugop;
    private javax.swing.JTextField txtnombrep;
    private javax.swing.JTextField txtpesop;
    private javax.swing.JTextField txttelefonop;
    private javax.swing.JTextField txttelemep;
    // End of variables declaration//GEN-END:variables
}
